spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL:jdbc:mysql://15.165.140.119:3306/aster?useSSL=false&allowPublicKeyRetrieval=true}
    username: ${DB_USER:aster}
    password: ${DB_PASSWORD:1234}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  redis:
    host: localhost
    port: 6379
jwt:
  header: Authorization
  prefix: Bearer
  secret: lhjljlasndflasjdkfasdkfnasdasjidkflajsdkfahsdfjkafewfawefwaefeawfw
  accessExpiration: 604800
key:
  secretKey: ${SECRET_KEY}
server:
  port: 8080
cloud:
  aws:
    credentials:
      accessKey: ${ACCESS-KEY:AKIA472XLIA4MZWDJ2YB}
      secretKey: ${SECRET-KEY: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}
    s3:
      bucket: ${BUCKET:kangsunbucket}
    region:
      static: ${STATIC:ap-northeast-2}
  stack:
    auto: false
